#ifndef ADC_CONFIG_H
#define ADC_CONFIG_H


#define ADC_INPUT_CHANNEL         CHANNEL0 
#define ADC_REF_SELECTION         AVCC //EXTERNAL_VOLT ,INTERNAL_VOLT
#define ADC_ENABLE                ENABLE
#define ADC_PRESCALER             PRESCALER_DIV_BY_64 // 2,4,8,16,32,64,128
#define ADC_INTERUPUT_ENABLE      ENABLE




#endif